version: '3.1'

services:
  go:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 9000:9000

  db:
    build: ./db
    image: postgres
    container_name: myapp_db
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_user_pass
      - POSTGRES_DB=app_db

  test_db:
    build: ./test_db
    image: test_postgres
    container_name: test_myapp_db
    restart: always
    volumes:
      - ./test_data:/var/lib/postgresql/data
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_user_pass
      - POSTGRES_DB=app_db
