# Use root/example as user/password credentials
version: '3.1'

services:
  go:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 9000:9000

  db:
    build: ./db
    image: postgres
    container_name: myapp_db
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
#      - ./data:/data
#      - ./postgres-dump:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_user_pass
      - POSTGRES_DB=app_db

#volumes:
#  postgres-dump:

#volumes:
#  data:

#volumes:
#  dbdata:
# docker exec -it id_cont bash